window.skill = {
	'skill' : {
		'skill_atk_up' : 'Tăng ATK',
		'skill_atk_down' : 'Giảm ATK',
		'skill_def_up' : 'Tăng DEF',
		'skill_def_down' : 'Giảm DEF',
		'skill_ct_up' : 'Tăng CT',
		'skill_ct_shorten' : 'Rút ngắn CT',
		'skill_ct_down' : 'Giảm CT',
		'skill_deal_dmg' : 'Gây sát thương',
		'skill_fixed_dmg' : 'Gây sát thương chuẩn',
		'skill_guard_up' : 'Tăng tỉ lệ bật khiên',
		'skill_guard_down' : 'Giảm tỉ lệ bật khiên',
		'skill_speed_up' : 'Tăng SPEED',
		'skill_speed_down' : 'Giảm SPEED',
		'skill_cut_hp' : 'Cắt máu',
		'skill_crit_up' : 'Tăng CRIT',
		'skill_crit_down' : 'Giảm CRIT',
		'skill_heal' : 'Hồi máu',
		'skill_blow_up' : 'Tăng tỉ lệ đẩy lùi',
		'skill_blow_down' : 'Giảm tỉ lệ đẩy lùi',
		'skill_silence_down' : 'Giảm khóa chiêu',
		'skill_silence_enemies' : 'Khóa chiêu',
		'skill_para_enemies' : 'Khóa hành động',
		'skill_lock_target' : 'Khóa mục tiêu',
	},
	'hidden_skill' : {
		'hiddenskill_atk_up' : 'Tăng ATK',
		'hiddenskill_atk_down' : 'Giảm ATK',
		'hiddenskill_def_up' : 'Tăng DEF',
		'hiddenskill_def_down' : 'Giảm DEF',
		'hiddenskill_ct_up' : 'Tăng CT',
		'hiddenskill_ct_down' : 'Giảm CT',
		'hiddenskill_deal_dmg' : 'Gây sát thương',
		'hiddenskill_fixed_dmg' : 'Gây sát thương chuẩn',
		'hiddenskill_guard_up' : 'Tăng tỉ lệ bật khiên',
		'hiddenskill_guard_down' : 'Giảm tỉ lệ bật khiên',
		'hiddenskill_speed_up' : 'Tăng SPEED',
		'hiddenskill_speed_down' : 'Giảm SPEED',
		'hiddenskill_cut_hp' : 'Cắt máu',
		'hiddenskill_crit_up' : 'Tăng CRIT',
		'hiddenskill_crit_down' : 'Giảm CRIT',
		'hiddenskill_heal' : 'Hồi máu',
		'hiddenskill_blow_up' : 'Tăng tỉ lệ đẩy lùi',
		'hiddenskill_blow_down' : 'Giảm tỉ lệ đẩy lùi',
		'hiddenskill_silence_down' : 'Giảm khóa chiêu',
	},
	'ability' : {
		'ability_prevent_para' : 'Ngăn tê liệt (paralysis)',
		'ability_prevent_silence': 'Ngăn khóa chiêu',
		'ability_prevent_crit': 'Ngăn Crit',
		'ability_prevent_stack_dmg': 'Ngăn dmg cộng dồn',
		'ability_heal': 'Hồi máu',
	},
	'target' : {
		'target_nearby' : 'Ở gần',
		'target_highest_atk' : 'ATK cao',
		'target_highest_speed' : 'SPEED cao',
		'target_highest_def' : 'DEF cao',
	},
}