window.skill = {
	'skill' : {
		'skill_atk_up' : 'Tăng ATK',
		'skill_atk_down' : 'Giảm ATK',
		'skill_def_up' : 'Tăng DEF',
		'skill_def_down' : 'Giảm DEF',
		'skill_ct_up' : 'Tăng tốc tích nộ',
		'skill_ct_shorten' : 'Cộng nộ',
		'skill_ct_down' : 'Giảm tốc tích nộ',
		'skill_ct_reduce' : 'Trừ nộ',
		'skill_deal_dmg' : 'Gây sát thương',
		'skill_fixed_dmg' : 'Gây sát thương chuẩn',
		'skill_guard_up' : 'Tăng tỉ lệ chặn đòn',
		'skill_guard_down' : 'Giảm tỉ lệ chặn đòn',
		'skill_speed_up' : 'Tăng SPEED',
		'skill_speed_down' : 'Giảm SPEED',
		'skill_cut_hp' : 'Cắt máu',
		'skill_crit_up' : 'Tăng CRIT',
		'skill_crit_down' : 'Giảm CRIT',
		'skill_heal' : 'Hồi máu',
		'skill_blow_up' : 'Tăng tỉ lệ đẩy lùi',
		'skill_blow_down' : 'Giảm tỉ lệ đẩy lùi',
		'skill_silence_down' : 'Giảm khóa chiêu',
		'skill_silence_enemies' : 'Khóa chiêu',
		'skill_bind_enemies' : 'Khóa hành động',
		'skill_bind_down' : 'Giảm khóa hành động',
		'skill_para_enemies' : 'Làm tê liệt',
		'skill_para_down' : 'Giảm tê liệt (paralysis)',
		'skill_lock_target' : 'Khóa mục tiêu',
		'skill_continuous_dmg_up' : 'Sát thương theo thời gian',
		'skill_miss_up' : 'Tăng tỉ lệ đánh trượt',
		'skill_accurate_down' : 'giảm tỉ lệ chính xác',
		'skill_stat_down' : 'giảm chỉ số',
	},
	'hidden_skill' : {
		'hs_atk_up' : 'Tăng ATK',
		'hs_atk_down' : 'Giảm ATK',
		'hs_hp_up' : 'Tăng HP',
		'hs_hp_down' : 'Giảm HP',
		'hs_def_up' : 'Tăng DEF',
		'hs_def_down' : 'Giảm DEF',
		'hs_ct_up' : 'Tăng tốc CT',
		'hs_ct_down' : 'Giảm tốc CT',
		'hs_deal_dmg' : 'Gây sát thương',
		'hs_fixed_dmg' : 'Gây sát thương chuẩn',
		'hs_guard_up' : 'Tăng tỉ lệ bật khiên',
		'hs_guard_down' : 'Giảm tỉ lệ bật khiên',
		'hs_speed_up' : 'Tăng SPEED',
		'hs_speed_down' : 'Giảm SPEED',
		'hs_cut_hp' : 'Cắt máu',
		'hs_crit_up' : 'Tăng CRIT',
		'hs_crit_down' : 'Giảm CRIT',
		'hs_heal' : 'Hồi máu',
		'hs_blow_up' : 'Tăng tỉ lệ đẩy lùi',
		'hs_blow_down' : 'Giảm tỉ lệ đẩy lùi',
		'hs_silence_down' : 'Giảm khóa chiêu',
		'hs_para_down' : 'Giảm tê liệt',
		'hs_bind_down' : 'Giảm trói',
		'hidden_skill_accuracy_enemy_down' : 'Giảm chính xác',
		'hidden_skill_rcv_up' : 'Tăng RCV',
		'hs_miss_up' : 'Tăng tỉ lệ đánh trượt',
	},
	'ability' : {
		'ability_prevent_para' : 'Ngăn tê liệt (paralysis)',
		'ability_prevent_silence': 'Ngăn khóa chiêu',
		'ability_prevent_bind': 'Ngăn trói',
		'ability_prevent_crit': 'Ngăn Crit',
		'ability_prevent_stack_dmg': 'Ngăn chặn sát thương theo thời gian (Độc)',
		'ability_heal': 'Hồi máu',
		'ability_dmg_reduce': 'Giảm sát thương',
	},
	'target' : {
		'target_nearby' : 'Ở gần',
		'target_highest_atk' : 'ATK cao',
		'target_highest_speed' : 'SPEED cao',
		'target_highest_def' : 'DEF cao',
		'target_low_hp' : 'HP thấp',
		'target_highest_hp' : 'HP cao',
	},
}