window.skill = {
	'skill' : {
		'skill_atk_up' : 'Tăng ATK',
		'skill_atk_down' : 'Giảm ATK',
		'skill_def_up' : 'Tăng DEF',
		'skill_def_down' : 'Giảm DEF',
		'skill_ct_up' : 'Tăng tốc CT',
		'skill_ct_shorten' : 'Rút ngắn CT',
		'skill_ct_down' : 'Giảm tốc CT',
		'skill_deal_dmg' : 'Gây sát thương',
		'skill_fixed_dmg' : 'Gây sát thương chuẩn',
		'skill_guard_up' : 'Tăng tỉ lệ bật khiên',
		'skill_guard_down' : 'Giảm tỉ lệ bật khiên',
		'skill_speed_up' : 'Tăng SPEED',
		'skill_speed_down' : 'Giảm SPEED',
		'skill_cut_hp' : 'Cắt máu',
		'skill_crit_up' : 'Tăng CRIT',
		'skill_crit_down' : 'Giảm CRIT',
		'skill_heal' : 'Hồi máu',
		'skill_blow_up' : 'Tăng tỉ lệ đẩy lùi',
		'skill_blow_down' : 'Giảm tỉ lệ đẩy lùi',
		'skill_silence_down' : 'Giảm khóa chiêu',
		'skill_silence_enemies' : 'Khóa chiêu',
		'skill_bind_enemies' : 'Khóa hành động',
		'skill_bind_down' : 'Giảm khóa hành động',
		'skill_para_enemies' : 'Làm tê liệt',
		'skill_para_down' : 'Giảm tê liệt (paralysis)',
		'skill_lock_target' : 'Khóa mục tiêu',
		'skill_continuous_dmg_up' : 'Tấn công liên hoàn +',
		'skill_miss_up' : 'Tăng tỉ lệ đánh trượt',
		'skill_accurate_down' : 'giảm tỉ lệ chính xác',
	},
	'hidden_skill' : {
		'hiddenskill_atk_up' : 'Tăng ATK',
		'hiddenskill_atk_down' : 'Giảm ATK',
		'hiddenskill_def_up' : 'Tăng DEF',
		'hiddenskill_def_down' : 'Giảm DEF',
		'hiddenskill_ct_up' : 'Tăng tốc CT',
		'hiddenskill_ct_down' : 'Giảm tốc CT',
		'hiddenskill_deal_dmg' : 'Gây sát thương',
		'hiddenskill_fixed_dmg' : 'Gây sát thương chuẩn',
		'hiddenskill_guard_up' : 'Tăng tỉ lệ bật khiên',
		'hiddenskill_guard_down' : 'Giảm tỉ lệ bật khiên',
		'hiddenskill_speed_up' : 'Tăng SPEED',
		'hiddenskill_speed_down' : 'Giảm SPEED',
		'hiddenskill_cut_hp' : 'Cắt máu',
		'hiddenskill_crit_up' : 'Tăng CRIT',
		'hiddenskill_crit_down' : 'Giảm CRIT',
		'hiddenskill_heal' : 'Hồi máu',
		'hiddenskill_blow_up' : 'Tăng tỉ lệ đẩy lùi',
		'hiddenskill_blow_down' : 'Giảm tỉ lệ đẩy lùi',
		'hiddenskill_silence_down' : 'Giảm khóa chiêu',
		'hiddenskill_para_down' : 'Giảm tê liệt',
		'hiddenskill_bind_down' : 'Giảm trói',
		'hidden_skill_accuracy_enemy_down' : 'Giảm chính xác',
		'hidden_skill_rcv_up' : 'Tăng RCV',
		'hiddenskill_miss_up' : 'Tăng tỉ lệ đánh trượt',
	},
	'ability' : {
		'ability_prevent_para' : 'Ngăn tê liệt (paralysis)',
		'ability_prevent_silence': 'Ngăn khóa chiêu',
		'ability_prevent_bind': 'Ngăn trói',
		'ability_prevent_crit': 'Ngăn Crit',
		'ability_prevent_stack_dmg': 'Ngăn chặn sát thương theo thời gian (Độc)',
		'ability_heal': 'Hồi máu',
	},
	'target' : {
		'target_nearby' : 'Ở gần',
		'target_highest_atk' : 'ATK cao',
		'target_highest_speed' : 'SPEED cao',
		'target_highest_def' : 'DEF cao',
		'target_low_hp' : 'HP thấp',
		'target_highest_hp' : 'HP cao',
	},
}